### ISSUE TITLE
npm install doesn't work 

### ISSUE THREAD

**Issue by edi9999** [ForbesLindesay/spawn-sync#11]
Since spawn-sync v1.0.5, they is an error in  npm install : 

```
> spawn-sync@1.0.5 postinstall /usr/local/lib/node_modules/clients-cli/node_modules/spawn-sync
> node postinstall


/usr/local/lib/node_modules/clients-cli/node_modules/spawn-sync/postinstall.js:38
      throw err;
            ^
Error: Command failed: npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v0.10.31
npm ERR! npm  v2.1.17

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/clients-cli/node_modules/spawn-sync/npm-debug.log

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "." "-g"
npm ERR! node v0.10.31
npm ERR! npm  v2.1.17
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.5 postinstall: `node postinstall`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.5 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.
```

The error doesn't occur on 1.0.2

**Comment by ForbesLindesay** [comment]
Could you post the contents of `/usr/local/lib/node_modules/clients-cli/node_modules/spawn-sync/npm-debug.log`

**Comment by edi9999** [comment]
That file doesn't exist. 

Here's a link to the npm-debug.log :+1: 

https://gist.github.com/2652a7d59f7d6404aa09

The issue is only happening when installing with the global flag (-g), and I need to run it with sudo. 

Here is the error that is happening (I guess)

```
1651 info install spawn-sync@1.0.5
1652 info postinstall spawn-sync@1.0.5
1653 verbose unsafe-perm in lifecycle false
1654 info spawn-sync@1.0.5 Failed to exec postinstall script
1655 verbose unlock done using /home/edgar/.npm/_locks/spawn-sync-f9b3282d6c80b99b.lock for /usr/local/lib/node_modules/clients-cli/node_modules/spawn-sync
1656 verbose about to build /usr/local/lib/node_modules/clients-cli
1657 verbose unlock done using /home/edgar/.npm/_locks/clients-cli-a9e0525d802c18eb.lock for /usr/local/lib/node_modules/clients-cli
1658 verbose stack Error: spawn-sync@1.0.5 postinstall: `node postinstall`
1658 verbose stack Exit status 8
1658 verbose stack at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
1658 verbose stack at EventEmitter.emit (events.js:98:17)
1658 verbose stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
1658 verbose stack at ChildProcess.emit (events.js:98:17)
1658 verbose stack at maybeClose (child_process.js:756:16)
1658 verbose stack at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

**Comment by zenorocha** [comment]
Same here.

**Comment by Mte90** [comment]
confirmed the previous version (1.0.4) work without problem

**Comment by akoval** [comment]
after installation with 
```
npm install spawn-sync --ignore-scripts
```

is see that package.json has owner root. Other files has valid user as owner

So maybe it will help as temp workaround:
```
npm install spawn-sync --ignore-scripts
chown myuser:myusergroup ./node_modules/spawn-sync/package.json
node ./node_modules/spawn-sync/postinstall.sh
```

**Comment by leobalter** [comment]
As mentioned on #14, this error happens due to a permission issue when the user is not root.

**Comment by pvledoux** [comment]
Same here with 1.0.6. It's blocking because this a dependency of imagemin.

**Comment by jdwilliams15** [comment]
Install fails for me on both ubuntu and mac due to the permission issue

**Comment by akoval** [comment]
the workaround for direct dependency:
1) install with npm with --ignore-scripts flag.
2) fix permissions for postinstall script. 
3) run postinstall.js manually

If it is not your direct dependency - make it direct:
1) Add this library as direct dependency (npm install spawn-sync --ignore-scripts --save).

**Comment by jdwilliams15** [comment]
I trying to install cross-spawn which depends on this. I'll give the workaround a try, thanks for that. I read the postinstall script and I'm unsure as to what the exact purpose for it is. Is there some issue with installation of spawn-sync's dependencies?

**Comment by akoval** [comment]
If you are using fresh nodejs spawn-sync should works like wrapper (because new nodejs already have such functionality). 

As I understood idea of postinstall is to add some deps for old version of nodejs. But I see these extra dependencies in package.json. So looks like it doesn't make sense to run postinstall.js at all

**Comment by akoval** [comment]
to avoid such problems in the future - try to freeze all you versions.

1) npm shrinkwrap (in new npm 3 it will be better to use)
2) commit all your dependencies in your repo and clear all package.json with 
*, ~, ^ in library versions (our private repo). Using such wildcards is bad practice. In my project we used library which has:

spawn-sync: ^1.0.1

So latest MINOR update broke everything:)

**Comment by ForbesLindesay** [comment]
The minor upgrade should not have broken anything, but npm clearly has very buggy/brittle handling of post-install scripts.  You could try with the latest update and see if it fixes things?

**Comment by jdwilliams15** [comment]
Just attempted install on my mac osx. Did 'sudo npm install spawn-sync'. Same issue
-
> spawn-sync@1.0.8 postinstall /Users/James/Projects/shell/node_modules/spawn-sync
> node postinstall


fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/Users/James/Projects/shell/node_modules/spawn-sync/package.json'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at Object.<anonymous> (/Users/James/Projects/shell/node_modules/spawn-sync/postinstall.js:35:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "spawn-sync"
npm ERR! node v0.10.35
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.8 postinstall: `node postinstall`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.8 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

**Comment by ForbesLindesay** [comment]
The latest version should fail more gracefully in some cases where npm does not get successfully execed. It will print a warning to the console but should still "work".

**Comment by gmahomarf** [comment]
Not sure if relevant, but I'm having issues installing on Windows (as a dependency of imagemin). The postinstall script never exits. My TeamCity build agent spent the entire night stuck on postinstall (8+ hours). I've checked permissions, and everything appears to be in order. The TC user has full control over the entire source directory tree. I specifically went in and checked the node_modules/spawn-sync directory and every file within it while it was stuck executing. Permissions are in order.

**Comment by nyakto** [comment]
io.js v2.0.2, spawn-sync@1.0.11
similar error, postinstall script fails (checked spawn-sync@1.0.2 - worked well)
[npm-debug.log](https://gist.github.com/nyakto/d4bf47c95b2fba1f1f15)

**Comment by nyakto** [comment]
I think now I understand what happens.

```npm``` downgrades permissions while running scripts (for security purpose).
This issue occurs when running npm install as superuser.

You can still install everything as superuser, but you have to run ```npm install spawn-sync --unsafe-perm```

Hope it helps

**Comment by avances123** [comment]
no Errors with --unsafe-perm, but I get:
```
Native thread-sleep not available.
This will result in much slower performance.
You should re-install spawn-sync if possible.
```

**Comment by quentindelattre** [comment]
Same problem here... I'm trying to install yeoman with npm and this comes up

```
> spawn-sync@1.0.11 postinstall /usr/local/lib/node_modules/yo/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

sh: node: command not found
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! spawn-sync@1.0.11 postinstall: `node postinstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.11 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/XXXX

/npm-debug.log
```

[npm-debug.log](https://gist.github.com/quentindelattre/bee93e2a2f6535c1a7c4#file-npm-debug-log)

**Comment by ricricucit** [comment]
same here

**Comment by ricricucit** [comment]
@quentindelattre same here. Updating node to 0.12.4 solved my problem.

**Comment by quentindelattre** [comment]
I'am already running 0.12.4

I'll try a fresh reinstall of node.

**Comment by quentindelattre** [comment]
Well, I followed this (http://www.johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/) and reinstalled Node, NPM, Gulp, Bower, Yeoman and Grunt, and it works now

**Comment by mittalsumeet** [comment]
I was getting exactly the same error. Updating node to v.0.12.4 fixed it.
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
node -v

**Comment by quentindelattre** [comment]
I thought I had solved it but no... Still the same problem to install Yeoman...

It's driving me crazy !

**Comment by quentindelattre** [comment]
After many many many (many) reinstalls, and updates it finally worked !

No idea how nor why however…

**Comment by billchalmers** [comment]
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
node -v

this from mittalsummeet worked for me

**Comment by raphaelpor** [comment]
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
node -v

This from mittalsummeet worked for me (2)

**Comment by icyflame** [comment]
```shell
sudo npm install -g --unsafe-perm yo
```

This worked for me! Although, it gave me quite a few warnings at the end of the install!

**Comment by hellomedia** [comment]
worked for me updating node to 0.12.4 as suggested in https://github.com/ForbesLindesay/spawn-sync/issues/11#issuecomment-110253433

**Comment by Ting-y** [comment]
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
node -v

This from mittalsummeet worked for me (3)

**Comment by marketcalls** [comment]
sudo npm install -g --unsafe-perm yo

This solved for me!

**Comment by jguffey** [comment]
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
node -v

+1 works for me on Mac 10.11 (build 15A204h).

**Comment by liamdawson** [comment]
> sudo npm cache clean -f
> sudo npm install -g n
> sudo n stable
> node -v

Can confirm this fixed my issue. This basically just updated nodejs?

**Comment by icyflame** [comment]
Yes, it cleared the npm cache. n Is the version manager for nodeJS. And the last line, sudo n stable, will update it to the latest version for that particular project/module.

**Comment by jeffwagar** [comment]
mittalsumeet you are a genius and fixed all my  problems... well most of my problems... Thank you!

**Comment by hotterd** [comment]
sudo npm install -g --unsafe-perm yo

worked for me.

**Comment by ForbesLindesay** [comment]
I'd be surprised if anyone still has problems after the latest release.  If you do, please let me know and I'll reopen.

**Comment by igorbb** [comment]
I am still having this issue.
This msg arrises when installing the atom-editor 

Node: v0.12.7
npm: v2.13.5

    Native thread-sleep not available.
    This will result in much slower performance, but it will still work.
    You should re-install spawn-sync or upgrade to the lastest version of node if possible.

**Comment by naorunaoru** [comment]
I'm having the same issues as @igorbb.
Node: v0.12.7
npm: v2.13.3

**Comment by igorbb** [comment]
@naorunaoru  I am trying a few things...

Se if this works for you ..


    npm install yo

**Comment by naorunaoru** [comment]
Installed successfully, got “everything looks all right”, but nothing changed.

On 20 Aug 2015 at 17:53:15, igorbb (notifications@github.com) wrote:

@naorunaoru I am trying a few things...

Se if this works for you ..

npm install yo

**Comment by naorunaoru** [comment]
I'm having the same issues as @igorbb.
Node: v0.12.7
npm: v2.13.3

**Comment by ScriptorNY** [comment]
I'm also having this issue

**Comment by igorbb** [comment]
Should we open a new issue @ForbesLindesay  ?

**Comment by ForbesLindesay** [comment]
If you like, although unless someone comes with a pull request containing a fix, I'm unlikely to have time to look into it.

**Comment by deCodeIt** [comment]
mittalsumeet.. You are a saviour
Was stucked with the same issue forever

**Comment by pluswave** [comment]
has this issue on OSX 10.11

> spawn-sync@1.0.14 postinstall /Users/zzb/nvm/versions/node/v4.2.2/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

>npm WARN engine cordova-js@4.0.0: wanted: {"node":"~0.10.x"} (current: {"node":"4.2.2","npm":"2.14.7"})
>npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.2.2","npm":"2.14.7"})

**Comment by bearpaw** [comment]
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
node -v
```
+1 worked for me on Ubuntu 14.04

```
$ sudo n stable

     install : node-v5.6.0
       mkdir : /usr/local/n/versions/node/5.6.0
       fetch : https://nodejs.org/dist/v5.6.0/node-v5.6.0-linux-x64.tar.gz
   installed : v5.6.0
```

**Comment by ssagari** [comment]
Thanks bearpaw, I was also stuck with problem faced by igorbb and this solution worked for me...
