### ISSUE TITLE
Strings, not buffer objects

### ISSUE THREAD

**Issue by leobalter** [ForbesLindesay/spawn-sync#12]
the result object for the fallback method have Buffer objects on the `stdout` and `stderr` properties. 

iojs and 0.12 both return string values for them instead of buffer objects.

It would be good to fix this for a stardard utilization.

**Comment by ForbesLindesay** [comment]
This is true when the `encoding` option is manually set to something other than `buffer`.  It shouldn't be too difficult to fix, just edit [./lib/worker.js#L34-43](https://github.com/ForbesLindesay/spawn-sync/blob/81ed72d97cd85982e167512420cd563f3e1b4500/lib/worker.js#L34-L43) by adding something like:

```js
if (options.encoding && options.encoding !== 'buffer') {
  stdout = stdout.toString(options.encoding);
  stderr = stderr.toString(options.encoding);
}
```

Do you feel like submitting a pull request?

**Comment by leobalter** [comment]
Sure! I'll send it by tomorrow morning.
