### ISSUE TITLE
npm install does not work with spaces in path (path to npm not correctly quoted)

### ISSUE THREAD

**Issue by m42jkuehle** [ForbesLindesay/spawn-sync#19]
When node is installed in a path with spaces in the name, the postinstall command failes with the following error:

```
> spawn-sync@1.0.8 postinstall D:\7560\64\src\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin\node_modules\bin-wrapper\node_modules\bin-check\node_modules\spawn-sync
> node postinstall


D:\7560\64\src\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin\node_modules\bin-wrapper\node_modules\bin-check\node_modules\spawn-sync\postinstall.js:40
      throw err;
            ^
Error: Command failed: 'C:\Program' is not recognized as an internal or external command,

operable program or batch file.


    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

Related commit: f1de876524bda9c5c93444081fbb777ef53ca413

I assume the reason is, that the `process.env.npm_execpath` variable contains spaces. On my machine its "C:\Progam Files\nodejs".

**Comment by m42jkuehle** [comment]
I found a workaround on windows:

You can use the short path name in the environment variable, e.g. use "C:\PROGRA~1\nodejs\" instead of "C:\Progam Files\nodejs\".

(You can find out the correct short name of your folder by executing `dir /x` in the parent folder.)

**Comment by ForbesLindesay** [comment]
Please try 1.0.9 and let me know if that still breaks for you?

**Comment by m42jkuehle** [comment]
I assume it will work (I can only test this next Monday).

But I think now it will fail, if the environment variable is not set. Because the left part of the `||` will not be an empty string anymore but two quotes (`""`).

**Comment by ForbesLindesay** [comment]
I spotted that just after publishing.  1.0.10 should work even if the environment variable is not set.  Let me know if it still fails on Windows and I will reopen.
