### ISSUE TITLE
fwd: spawn-sync 1.0.13 FAILs at 'node postinstall'

### ISSUE THREAD

**Issue by pgnd** [ForbesLindesay/spawn-sync#28]
"Please let @ForbesLindesay know by forwarding this issue over to https://github.com/ForbesLindesay/spawn-sync"

fwd'ing, per request, from:  https://github.com/Glavin001/atom-beautify/issues/467

Running

```
atom --version
	1.0.3-9774b20
node -v
	v2.4.0
npm -v
	2.13.0
```
Upgrading atom-beautify from installed v0.28.7 to v0.28.8 FAILs:
```
Updating to “atom-beautify@0.28.8” failed.

> spawn-sync@1.0.13 postinstall /tmp/apm-install-dir-115617-5652-1i1ck6n/node_modules/atom-beautify/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/apm-install-dir-115617-5652-1i1ck6n/node_modules/atom-beautify/node_modules/cross-spawn/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
npm ERR! Linux 4.1.1-2.gcac28b3-desktop
npm ERR! argv "/usr/local/share/atom/resources/app/apm/bin/node" "/usr/local/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/pgnd/.atom/.apm/.apmrc" "--userconfig" "/home/pgnd/.atom/.apmrc" "install" "/tmp/d-115617-5652-1qpfmy7/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.13 postinstall: `node postinstall`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.13 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115617-5652-1i1ck6n/npm-debug.log

ls -al /tmp/apm-install-dir-115617-5652-1i1ck6n/npm-debug.log
	ls: cannot access /tmp/apm-install-dir-115617-5652-1i1ck6n/npm-debug.log: No such file or directory
```

**Comment by ForbesLindesay** [comment]
This seems like an error in atom's package manager.  It should be downloading postinstall as part of the spawn-sync package.  You could try re-installing with the additional option:

```
--ignore-scripts
```

**Comment by evanliomain** [comment]
Hi, i have the same issue installing `generator-meteor-polymer` on linux :
```shell
sudo npm install -g generator-meteor-polymer

> spawn-sync@1.0.13 postinstall /home/evan/npm/lib/node_modules/generator-meteor-polymer/node_modules/yo/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

module.js:338
    throw err;
          ^
Error: Cannot find module '/home/evan/npm/lib/node_modules/generator-meteor-polymer/node_modules/yo/node_modules/cross-spawn/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
\
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "generator-meteor-polymer"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.13 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.13 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/evan/workspace/test/meteorApps/simple-todos/npm-debug.log
```

**Comment by tabyasu** [comment]
I was able to resolve.

    sudo chown -R loginuser:staff /Applications/Atom.app
    sudo chown -R loginuser:staff /Users/loginuser/.atom/

loginuser, please replaced by itself.

    apm -v
    apm  1.0.4
    npm  2.13.3
    node 0.10.40

    ATOM Version 1.0.11

The following problem has been resolved.

    MacBook-Air:Applications loginuser$ sudo apm stars --install
    Installing Sublime-Style-Column-Selection to /Users/loginuser/.atom/packages ✓
    Installing accents-ui to /Users/loginuser/.atom/packages ✓
    Installing atom-beautify to /Users/loginuser/.atom/packages ✗

    > spawn-sync@1.0.13 postinstall /private/tmp/apm-install-dir-115810-36967-gewmyl/node_modules/atom-beautify/node_modules/cross-spawn/node_modules/spawn-sync
    > node postinstall


    shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

    node.js:844
        var cwd = process.cwd();
                          ^
    Error: EACCES, permission denied
        at Function.startup.resolveArgv0 (node.js:844:23)
        at startup (node.js:58:13)
        at node.js:935:3
    npm ERR! Darwin 14.5.0
    npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/loginuser/.atom/.apm/.apmrc" "--userconfig" "/Users/loginuser/.atom/.apmrc" "install" "/private/tmp/d-115810-36967-1938zxe/package.tgz" "--target=0.22.0" "--arch=x64"
    npm ERR! node v0.10.40
    npm ERR! npm  v2.13.3
    npm ERR! code ELIFECYCLE

    npm ERR! spawn-sync@1.0.13 postinstall: `node postinstall`
    npm ERR! Exit status 8
    npm ERR! 
    npm ERR! Failed at the spawn-sync@1.0.13 postinstall script 'node postinstall'.
    npm ERR! This is most likely a problem with the spawn-sync package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node postinstall
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls spawn-sync
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /private/tmp/apm-install-dir-115810-36967-gewmyl/npm-debug.log

**Comment by sss4r** [comment]
I also get this exact error when attempting to install atom-beautify. I tried --ignore-scripts and the chown solution above to no avail. Please advise, thank you.

**Comment by tomasdelima** [comment]
I noticed I was missing the command `node`, even having Node.js installed in my machine (Ubuntu 15.10)
So I copied the `nodejs` file into the `node`:
```sh
which nodejs   # > /usr/bin/nodejs
sudo cp /usr/bin/nodejs /usr/bin/node
```

This was enough to solve my problems! Maybe there is a fancier (and more intelligent) way to fix this.
Anyone?

**Comment by ForbesLindesay** [comment]
Known problem, from the README:

> Some package managers made a stupid decision to rename the node executable to nodejs for their platform. This breaks compatibility with lots of modules. If you normally use nodejs instead of node, you should check out http://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04 for possible fixes.
