### ISSUE TITLE
'node postinstall' failing with error ENOENT

### ISSUE THREAD

**Issue by chandlerkent** [ForbesLindesay/spawn-sync#29]
A recent update to one of our dependencies pulled in spawn-sync which is consistently causing npm install to fail on our build servers. Note that our build servers are running Windows.

Here's the full error trace:

```
111127 verbose stack Error: spawn-sync@1.0.13 postinstall: `node postinstall`
111127 verbose stack spawn C:\Windows\system32\cmd.exe ENOENT
111127 verbose stack     at exports._errnoException (util.js:746:11)
111127 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
111127 verbose stack     at child_process.js:1144:20
111127 verbose stack     at process._tickCallback (node.js:355:11)
111128 verbose pkgid spawn-sync@1.0.13
111129 verbose cwd C:\BuildAgents\WorkFolders\1-3\48dcf735\MarketingOps.UI
111130 error Windows_NT 6.3.9600
111131 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
111132 error node v0.12.7
111133 error npm  v2.11.3
111134 error file C:\Windows\system32\cmd.exe
111135 error path C:\Windows\system32\cmd.exe
111136 error code ELIFECYCLE
111137 error errno ENOENT
111138 error syscall spawn C:\Windows\system32\cmd.exe
111139 error spawn-sync@1.0.13 postinstall: `node postinstall`
111139 error spawn C:\Windows\system32\cmd.exe ENOENT
111140 error Failed at the spawn-sync@1.0.13 postinstall script 'node postinstall'.
111140 error This is most likely a problem with the spawn-sync package,
111140 error not with npm itself.
111140 error Tell the author that this fails on your system:
111140 error     node postinstall
111140 error You can get their info via:
111140 error     npm owner ls spawn-sync
111140 error There is likely additional logging output above.
111141 verbose exit [ 1, true ]
```

**Comment by roecrew** [comment]
I'm getting the same thing on El Capitan.

sh: node: command not found
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "magsearch"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.13 postinstall: `node postinstall`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.13 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by jamescarroll** [comment]
We have been experiencing the same issues on our Windows based build servers, too. Problem seems to have crept in some time on or before 21/08/15.

```
[09:40:50][npm install] npm ERR! Windows_NT 6.1.7601
[09:40:50][npm install] npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
[09:40:50][npm install] npm ERR! node v0.12.4
[09:40:50][npm install] npm ERR! npm  v2.10.1
[09:40:50][npm install] npm ERR! file C:\Windows\system32\cmd.exe
[09:40:50][npm install] npm ERR! path C:\Windows\system32\cmd.exe
[09:40:50][npm install] npm ERR! code ELIFECYCLE
[09:40:50][npm install] npm ERR! errno ENOENT
[09:40:50][npm install] npm ERR! syscall spawn C:\Windows\system32\cmd.exe
[09:40:50][npm install] 
[09:40:50][npm install] npm ERR! spawn-sync@1.0.13 postinstall: `node postinstall`
[09:40:50][npm install] npm ERR! spawn C:\Windows\system32\cmd.exe ENOENT
[09:40:50][npm install] npm ERR! 
[09:40:50][npm install] npm ERR! Failed at the spawn-sync@1.0.13 postinstall script 'node postinstall'.
[09:40:50][npm install] npm ERR! This is most likely a problem with the spawn-sync package,
[09:40:50][npm install] npm ERR! not with npm itself.
[09:40:50][npm install] npm ERR! Tell the author that this fails on your system:
[09:40:50][npm install] npm ERR!     node postinstall
[09:40:50][npm install] npm ERR! You can get their info via:
[09:40:50][npm install] npm ERR!     npm owner ls spawn-sync
[09:40:50][npm install] npm ERR! There is likely additional logging output above.
[09:40:55][npm install] 
[09:40:55][npm install] npm ERR! Please include the following file with any support request:
[09:40:55][npm install] Process exited with code 1
```

**Comment by DuBistKomisch** [comment]
Same issue trying to run `npm install` on Windows:

```
npm verb stack Error: spawn-sync@1.0.13 postinstall: `node postinstall`
npm verb stack spawn C:\Windows\system32\cmd.exe ENOENT
npm verb stack     at exports._errnoException (util.js:746:11)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
npm verb stack     at child_process.js:1144:20
npm verb stack     at process._tickCallback (node.js:355:11)
npm verb pkgid spawn-sync@1.0.13
npm verb cwd C:\Users\Vivi\Documents\GitHub\vivi-chrome2\frontend
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\np
m-cli.js" "--verbose" "install"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! file C:\Windows\system32\cmd.exe
npm ERR! path C:\Windows\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd.exe

npm ERR! spawn-sync@1.0.13 postinstall: `node postinstall`
npm ERR! spawn C:\Windows\system32\cmd.exe ENOENT
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.13 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
```

**Comment by waltertamboer** [comment]
This is still the case, would be nice if this got fixed.

**Comment by jamescarroll** [comment]
Our CI server is now building correctly with no issues being thrown from this package - can anyone else confirm?

**Comment by waltertamboer** [comment]
@jamescarroll I can confirm, it works again.

**Comment by chandlerkent** [comment]
What changed? I don't see any commits since this issue was opened that would resolve this.

**Comment by jamescarroll** [comment]
@chandlerkent, I have a feeling that other modules higher up the dependency tree will have adjusted their package json to either remove the dependency or fix it to an earlier version. Would take some digging to be certain!

**Comment by ForbesLindesay** [comment]
This is definitely an npm issue, so it may just be that it's been fixed in a newer version of npm.

**Comment by zhouhao27** [comment]
add --ignore-scripts may solve the issue.

**Comment by chandlerkent** [comment]
@ForbesLindesay, thanks. We removed the dependency a while ago to get around this, so we aren't able to confirm if this is working again. If others say it is, feel free to close this issue.

**Comment by DuBistKomisch** [comment]
This is also no longer happening for us.

**Comment by ForbesLindesay** [comment]
I've added updated trouble shooting steps to the readme, hoping that resolves the issue for most people.  For people getting the ENOENT error in particular, I recommend trying updating npm:

    sudo npm install npm -g

Alternatively, update to node@4 and then run with `--ignore-scripts`

**Comment by unckleg** [comment]
Have this problem when: **npm start** 

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v9.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @0.1.0~prestart: @0.1.0
6 info lifecycle @0.1.0~start: @0.1.0
7 verbose lifecycle @0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle @0.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\user\PhpstormProjects\test\node_modules\.bin;C:\Users\user\bin;C:\Users\user\AppData\Local\Programs\Git\mingw64\bin;C:\Users\user\AppData\Local\Programs\Git\usr\local\bin;C:\Users\user\AppData\Local\Programs\Git\usr\bin;C:\Users\user\AppData\Local\Programs\Git\usr\bin;C:\Users\user\AppData\Local\Programs\Git\mingw64\bin;C:\Users\user\AppData\Local\Programs\Git\usr\bin;C:\Users\user\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\CCM;C:\wamp64\bin\php\php7.0.10;C:\Program Files (x86)\Mozilla Firefox;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Users\mducic\Documents\Selenium\ IEDriverServer.exe;C:\Program Files\nodejs;C:\Program Files (x86)\Skype\Phone;C:\Users\mducic\AppData\Roaming\Composer\vendor\bin;C:\Users\mducic\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\user\AppData\Local\Programs\Git\usr\bin\vendor_perl;C:\Users\user\AppData\Local\Programs\Git\usr\bin\core_perl
9 verbose lifecycle @0.1.0~start: CWD: C:\Users\user\PhpstormProjects\test
10 silly lifecycle @0.1.0~start: Args: [ '/d /s /c', 'react-scripts start' ]
11 info lifecycle @0.1.0~start: Failed to exec start script
12 silly lifecycle @0.1.0~start: Returned: code: -4058  signal: null
13 info lifecycle @0.1.0~start: Failed to exec start script
14 verbose stack Error: @0.1.0 start: `react-scripts start`
14 verbose stack spawn C:\Windows\System32\cmd.exe; ENOENT
14 verbose stack     at _errnoException (util.js:1031:13)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
14 verbose stack     at onErrorNT (internal/child_process.js:389:16)
14 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
14 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
15 verbose pkgid @0.1.0
16 verbose cwd C:\Users\user\PhpstormProjects\test
17 verbose Windows_NT 6.1.7601
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v9.2.0
20 verbose npm  v5.5.1
21 error file C:\Windows\System32\cmd.exe;
22 error path C:\Windows\System32\cmd.exe;
23 error code ELIFECYCLE
24 error errno ENOENT
25 error syscall spawn C:\Windows\System32\cmd.exe;
26 error @0.1.0 start: `react-scripts start`
26 error spawn C:\Windows\System32\cmd.exe; ENOENT
27 error Failed at the @0.1.0 start script.
27 error This is probably not a problem with npm. There is likely additional logging output above.
28 verbose exit [ 1, true ]`
