### ISSUE TITLE
node 0.10.x and npm@3 extraneous deps

### ISSUE THREAD

**Issue by bengl** [ForbesLindesay/spawn-sync#36]
When using node 0.10 and npm@3 (I tried with node@0.10.40 and npm@3.3.10), using spawn-sync as a subdependency results in extraneous dependencies being installed. Normally this wouldn't be an issue, but an internal client of mine was trying to then run `npm shrinkwrap`, which failed due to these extraneous dependencies.

A simple solution is to simply run `npm prune` to get rid of them, but it would be great if there was some solution to this that could be done in spawn-sync's `postinstall`.

Repro steps:

```
mkdir ~/spawnsynctest
$ cd ~/spawnsynctest
$ cat <<EOF > package.json
{
  "dependencies": {
    "grunt-sass": "~1.1.0"
  }
}
EOF
$ nvm use v0.10.40
$ npm i -g npm@3.3.10
$ npm i
$ npm ls > /dev/null
npm ERR! extraneous: concat-stream@1.5.1 /home/bengl/spawnsynctest/node_modules/concat-stream
npm ERR! extraneous: os-shim@0.1.3 /home/bengl/spawnsynctest/node_modules/os-shim
```

**Comment by ForbesLindesay** [comment]
This should be fixed if you install using 0.12, other than that I don't really have a good solution for this.

**Comment by tlhunter** [comment]
:+1:

**Comment by ForbesLindesay** [comment]
The latest version is just a stub with no postinstall script. It does require upgrading to a recent version of node.js
