### ISSUE TITLE
spawn-sync appears to cause problem with update to Atom package zotero-citations

### ISSUE THREAD

**Issue by cjpoor** [ForbesLindesay/spawn-sync#39]
I have not been able to update the zotero-citations for Markdown package on Atom editor.
I am on Mac OS X 10.10.5, Atom 1.3.2
The output I get is:

---

Updating to “zotero-citations@0.12.0” failed.Hide output…

> spawn-sync@1.0.15 postinstall /private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-11605-34980-bsfmfw/node_modules/zotero-citations/node_modules/sync-request/node_modules/spawn-sync
> node postinstall

npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/christopherpoor/.atom/.apm/.apmrc" "--userconfig" "/Users/christopherpoor/.atom/.apmrc" "install" "/private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/d-11605-34980-14b4cg8/package.tgz" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-11605-34980-bsfmfw/npm-debug.log

---

I also just tried
$ npm install spawn-sync

and got:

> spawn-sync@1.0.15 postinstall /Users/christopherpoor/node_modules/spawn-sync
> node postinstall

/Users/christopherpoor
├── spawn-sync@1.0.15
└── stable@0.1.5

npm WARN enoent ENOENT: no such file or directory, open '/Users/christopherpoor/package.json'
npm WARN christopherpoor No description
npm WARN christopherpoor No repository field.
npm WARN christopherpoor No README data
npm WARN christopherpoor No license field.

---

Any help much appreciated.

**Comment by ForbesLindesay** [comment]
Have you tried all the steps in https://github.com/ForbesLindesay/spawn-sync#installation ?

**Comment by cjpoor** [comment]
I will try them, thanks, but I want to make fairly sure I know what I am doing, so I am quickly running through "learning the shell." I did know how to make changes to the path in windows but I am not yet confident to do so in OS X. I'm guessing Bash is the equivalent of DOS and thought I should know it better for tweaking purposes.
However, I am somewhat at sea in general. For example, I don't know whether I "normally use nodejs instead of node."
As far as I can tell spawn-sync is installed under a folder called node-modules in my home dir. But there are also folders called nodejs and nodejs-devel under macports.

BTW I did try installing spawn-sync again and got:

> spawn-sync@1.0.15 postinstall /node_modules/spawn-sync
> node postinstall

/
└─┬ spawn-sync@1.0.15
  ├─┬ concat-stream@1.5.1
  │ ├── inherits@2.0.1
  │ ├─┬ readable-stream@2.0.5
  │ │ ├── core-util-is@1.0.2
  │ │ ├── isarray@0.0.1
  │ │ ├── process-nextick-args@1.0.6
  │ │ ├── string_decoder@0.10.31
  │ │ └── util-deprecate@1.0.2
  │ └── typedarray@0.0.6
  └── os-shim@0.1.3

npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

**Comment by cjpoor** [comment]
I went through all the recommended steps and spawn-sync installation now gives no errors.
However the update on Atom still gives:
****************
Updating to “zotero-citations@0.12.0” failed.Hide output…

> spawn-sync@1.0.15 postinstall /private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-11606-1048-ruclaz/node_modules/zotero-citations/node_modules/sync-request/node_modules/spawn-sync
> node postinstall


npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/christopherpoor/.atom/.apm/.apmrc" "--userconfig" "/Users/christopherpoor/.atom/.apmrc" "install" "/private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/d-11606-1048-z05wzu/package.tgz" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-11606-1048-ruclaz/npm-debug.log

**Comment by ForbesLindesay** [comment]
We get a lot of error reports from atom users. As I understand it, atom runs with a slightly forked version of node/npm and presumably they managed to fork a slightly broken version.

**Comment by retorquere** [comment]
Oh. Nice. Do you know of a place we could enter this issue?

**Comment by cjpoor** [comment]
The plot thickens!
ForbesLindesay posted the issue here
https://github.com/atom/atom/issues/7982

**Comment by hirenpatel20283** [comment]
Before you can continue, the latest Appcelerator software update needs to be downloaded.

Finding version 6.1.0 ... ✓
Validating security checksum ✓
Installing ... ✓
Compiling platform native modules ...
└ socket.io-client/ws ...Failed to install ws@0.4.32; it may not support your current OS.
└ external-editor/spawn-sync ... Failed to install spawn-sync@1.0.15; it may not support your current OS.
└ bunyan/dtrace-provider ... Failed to install dtrace-provider@0.8.0; it may not support your current OS.
└ bunyan/dtrace-provider ... Failed to install dtrace-provider@0.8.0; it may not support your current OS.
└ ldapjs/dtrace-provider ... Failed to install dtrace-provider@0.7.1; it may not support your current OS.
└ package/fsevents ... Failed to install fsevents@1.0.15; it may not support your current OS.
Installed!!

**Comment by hirenpatel20283** [comment]
I getting such error.Please let me know know if any one have suggestion on this error.

**Comment by ForbesLindesay** [comment]
The latest version is just a stub with no postinstall script. It does require upgrading to a recent version of node.js
