### ISSUE TITLE
Failed to intall  spawn-sync@1.0.15 postinstall: `node postinstall`

### ISSUE THREAD

**Issue by tovinayv** [ForbesLindesay/spawn-sync#46]
[ERROR] npm ERR! Linux 2.6.32-220.4.2.el6.x86_64
[ERROR] npm ERR! node v7.9.0
[ERROR] npm ERR! npm  v4.2.0
[ERROR] npm ERR! file sh
[ERROR] npm ERR! path sh
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno ENOENT
[ERROR] npm ERR! syscall spawn sh
[ERROR] 
[ERROR] npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
[ERROR] npm ERR! spawn sh ENOENT
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the spawn-sync package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node postinstall
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs spawn-sync
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls spawn-sync
[ERROR] npm ERR! There is likely additional logging output above.

**Comment by p4t0k** [comment]
If on Ubuntu, you need to install nodejs-legacy: sudo apt-get install nodejs-legacy

**Comment by ForbesLindesay** [comment]
The latest version is just a stub with no postinstall script. It does require upgrading to a recent version of node.js
