### ISSUE TITLE
Cannot find module '/root/.nvm/v6.11.3/lib/node_modules/yo/node_modules/spawn-sync/postinstall'

### ISSUE THREAD

**Issue by Santhoshas** [ForbesLindesay/spawn-sync#47]
node -v v6.11.3
nodejs -v v0.10.40
npm -v 5.4.0

OS:
NAME="CentOS Linux"
VERSION="7 

Error Details: 

npm install -g yo
/root/.nvm/v6.11.3/bin/yo -> /root/.nvm/v6.11.3/lib/node_modules/yo/lib/cli.js
/root/.nvm/v6.11.3/bin/yo-complete -> /root/.nvm/v6.11.3/lib/node_modules/yo/lib/completion/index.js

> spawn-sync@1.0.15 postinstall /root/.nvm/v6.11.3/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall

module.js:471
    throw err;
    ^

Error: Cannot find module '/root/.nvm/v6.11.3/lib/node_modules/yo/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by ForbesLindesay** [comment]
https://github.com/ForbesLindesay/spawn-sync#installation
